;;; dwindle-tests.el --- Behavioral tests for dwindle -*- lexical-binding: t; -*-

(setq load-prefer-newer t)

(require 'ert)
(require 'cl-lib)
(require 'dwindle)
(require 'dwindle-resize)

(defun dwindle-test--native-nodes (window)
  "Return WINDOW and its native descendants, including internal nodes."
  (let ((nodes (list window))
        (child (window-child window)))
    (while child
      (setq nodes (nconc nodes (dwindle-test--native-nodes child))
            child (window-next-sibling child)))
    nodes))

(defmacro dwindle-test--with-layout (&rest body)
  "Run BODY in an isolated, generously sized native window layout."
  (declare (indent 0) (debug t))
  `(let ((previous-mode dwindle-mode)
         (split-window-preferred-function split-window-preferred-function)
         (window-min-width 6)
         (window-min-height 3)
         (window-combination-resize nil)
         (previous-parameters
          (mapcar (lambda (window)
                    (cons window (mapcar (lambda (entry) (cons (car entry) (cdr entry)))
                                         (window-parameters window))))
                  (dwindle-test--native-nodes (frame-root-window)))))
     (unwind-protect
         (save-window-excursion
           (unwind-protect
               (progn
                 (dwindle-mode -1)
                 (delete-other-windows)
                 (set-frame-size (selected-frame) 160 90)
                 (dwindle-mode 1)
                 ,@body)
             (dwindle-mode -1)))
       ;; Window configurations omit nonpersistent application parameters.
       ;; Restore these explicitly so hostile callbacks cannot poison the
       ;; original root and make an unrelated later test fail.
       (dolist (entry previous-parameters)
         (when (window-valid-p (car entry))
           (dolist (parameter (window-parameters (car entry)))
             (set-window-parameter (car entry) (car parameter) nil))
           (dolist (parameter (cdr entry))
             (set-window-parameter (car entry) (car parameter) (cdr parameter)))))
       (when previous-mode (dwindle-mode 1)))))

(defun dwindle-test--windows ()
  "Return ordinary windows in native tree order."
  (cl-remove-if-not #'dwindle--managed-window-p
                    (window-list nil 'nomini (frame-first-window))))

(defun dwindle-test--create (count)
  "Create COUNT managed leaves and return them in creation order."
  (let ((windows (list (selected-window))))
    (dotimes (_ (1- count))
      (let ((new (dwindle-split)))
        (should (window-live-p new))
        (should (eq new (selected-window)))
        (setq windows (append windows (list new)))))
    windows))

(defun dwindle-test--snapshot ()
  "Record live window identity, geometry, and displayed buffer."
  (mapcar (lambda (window)
            (list window (window-edges window) (window-buffer window)))
          (window-list nil 'nomini (frame-first-window))))

(defun dwindle-test--assert-native-root ()
  "Check root and master queries against the live native window tree."
  (should (window-valid-p (dwindle-root-window)))
  (should (eq (dwindle-root-window) (window-main-window)))
  (should (eq (dwindle-master-window) (car (dwindle-test--windows)))))

(ert-deftest dwindle-splits-the-focused-window-within-its-existing-area ()
  (dwindle-test--with-layout
    (let* ((a (selected-window))
           (b (dwindle-split))
           (b-before (window-edges b)))
      (should (eq dwindle-split-policy 'focused))
      (select-window a)
      (let ((c (dwindle-split)))
        (should (equal (dwindle-test--windows) (list a c b)))
        (should (equal (window-edges b) b-before))
        (should (= (nth 3 (window-edges a)) (nth 1 (window-edges c))))
        (select-window a)
        (let ((c-before (window-edges c))
              (d (dwindle-split)))
          (should (equal (dwindle-test--windows) (list a d c b)))
          (should (equal (window-edges b) b-before))
          (should (equal (window-edges c) c-before))
          (should (= (nth 2 (window-edges a)) (nth 0 (window-edges d))))
          (should (eq a (dwindle-master-window)))
          (dwindle-test--assert-native-root))))))

(ert-deftest dwindle-tail-policy-retains-trailing-alternating-splits ()
  (dwindle-test--with-layout
    (let* ((dwindle-split-policy 'tail)
           (a (selected-window))
           (b (dwindle-split)))
      ;; The compatibility policy deliberately ignores changes in focus.
      (select-window a)
      (let ((c (dwindle-split)))
        (select-window a)
        (let ((d (dwindle-split)))
          (should (equal (dwindle-test--windows) (list a b c d)))
          (should (= (nth 2 (window-edges a)) (nth 0 (window-edges b))))
          (should (= (nth 3 (window-edges b)) (nth 1 (window-edges c))))
          (should (= (nth 2 (window-edges c)) (nth 0 (window-edges d))))
          (should (= (nth 0 (window-edges b)) (nth 0 (window-edges c))))
          (should (= (nth 1 (window-edges c)) (nth 1 (window-edges d))))
          (should (eq a (dwindle-master-window)))
          (dwindle-test--assert-native-root))))))

(ert-deftest dwindle-split-displays-the-requested-buffer ()
  (dwindle-test--with-layout
    (let ((buffer (generate-new-buffer " *dwindle-test*")))
      (unwind-protect
          (should (eq (window-buffer (dwindle-split buffer)) buffer))
        (kill-buffer buffer)))))

(ert-deftest dwindle-can-start-by-splitting-below ()
  (dwindle-test--with-layout
    (let* ((dwindle-first-split 'below)
           (top (selected-window))
           (bottom-left (dwindle-split))
           (bottom-right (dwindle-split)))
      (should (= (nth 3 (window-edges top))
                 (nth 1 (window-edges bottom-left))))
      (should (= (nth 2 (window-edges bottom-left))
                 (nth 0 (window-edges bottom-right))))
      (should (eq (dwindle-master-window) top)))))

(ert-deftest dwindle-deleting-every-leaf-promotes-native-siblings ()
  (dotimes (victim-index 6)
    (dwindle-test--with-layout
      (let* ((windows (dwindle-test--create 6))
             (victim (nth victim-index windows))
             (survivors (delq victim (copy-sequence windows))))
        (select-window victim)
        (dwindle-delete-window)
        (should-not (window-live-p victim))
        (should (equal (dwindle-test--windows) survivors))
        (should (cl-every #'window-live-p survivors))
        (should (eq (dwindle-master-window) (car survivors)))
        (dwindle-test--assert-native-root)
        (let* ((source (selected-window))
               (new (dwindle-split)))
          (should (eq (window-parent new) (window-parent source)))
          (should (cl-every #'window-live-p survivors))
          (should (= (length (dwindle-test--windows)) 6)))
        (dwindle-test--assert-native-root)))))

(ert-deftest dwindle-native-deletion-and-configuration-restore-have-no-stale-master ()
  (dwindle-test--with-layout
    (let* ((windows (dwindle-test--create 4))
           (master (car windows))
           (configuration (current-window-configuration)))
      (delete-window master)
      (should (eq (dwindle-master-window) (cadr windows)))
      (dwindle-test--assert-native-root)
      (set-window-configuration configuration)
      (should (eq (dwindle-master-window) master))
      (should (window-live-p master))
      (dwindle-test--assert-native-root)
      (delete-other-windows (car (last windows)))
      (should (eq (dwindle-master-window) (selected-window)))
      (dwindle-test--assert-native-root)
      (should (window-live-p (dwindle-split)))
      (dwindle-test--assert-native-root))))

(ert-deftest dwindle-repeated-split-delete-stays-responsive ()
  ;; Makefile also puts the entire Emacs process under an external timeout:
  ;; Lisp timers cannot interrupt every kind of recursive window-hook failure.
  (dwindle-test--with-layout
    (dotimes (round 40)
      (dwindle-test--create 6)
      (dotimes (deletion 5)
        (let* ((windows (dwindle-test--windows))
               (index (mod (+ round (* deletion 3)) (length windows))))
          (select-window (nth index windows))
          ;; Exercise Emacs's own deletion path as well as our command.
          (if (zerop (% deletion 2))
              (delete-window)
            (dwindle-delete-window))
          (dwindle-test--assert-native-root)))
      (should (= (length (dwindle-test--windows)) 1)))))

(ert-deftest dwindle-unsplittable-window-leaves-no-partial-layout ()
  (dwindle-test--with-layout
    (let ((window-min-width 300)
          (window-min-height 150)
          (before (dwindle-test--snapshot))
          (selected (selected-window)))
      (should-not (condition-case nil
                      (dwindle-split)
                    (error nil)))
      (should (equal before (dwindle-test--snapshot)))
      (should (eq selected (selected-window)))
      (dwindle-test--assert-native-root))))

(ert-deftest dwindle-side-window-survives-splits-deletion-and-resizing ()
  (dwindle-test--with-layout
    (let* ((main (selected-window))
           (buffer (generate-new-buffer " *dwindle-side*"))
           (side (display-buffer-in-side-window
                  buffer '((side . bottom) (window-height . 6)))))
      (unwind-protect
          (let ((edges (window-edges side)))
            (select-window main)
            (let ((windows (dwindle-test--create 4)))
              (should-not (dwindle--managed-window-p side))
              (should (eq (dwindle-root-window) (window-main-window)))
              (select-window main)
              (dwindle-expand-right)
              (delete-window (cadr windows))
              (should (window-live-p (dwindle-split)))
              (should (window-live-p side))
              (should (eq (window-buffer side) buffer))
              (should (equal (window-edges side) edges))
              (dwindle-test--assert-native-root)))
        (kill-buffer buffer)))))

(ert-deftest dwindle-recognizes-windows-owned-by-other-features ()
  (dwindle-test--with-layout
    (let* ((ordinary (selected-window))
           (other (split-window ordinary nil 'right))
           (parent (window-parent other))
           (calls 0)
           (callback (lambda (&rest _) (cl-incf calls))))
      (should (dwindle--managed-window-p ordinary))
      (should-not (dwindle--managed-window-p (minibuffer-window)))
      (set-window-dedicated-p other t)
      (should-not (dwindle--managed-window-p other))
      (set-window-dedicated-p other nil)
      (dolist (parameter '(popup no-other-window dwindle-ignore no-delete-other-windows))
        (set-window-parameter other parameter t)
        (should-not (dwindle--managed-window-p other))
        (set-window-parameter other parameter nil))
      (dolist (parameter '(split-window delete-window delete-other-windows))
        (set-window-parameter other parameter callback)
        (should-not (dwindle--managed-window-p other))
        (set-window-parameter other parameter nil))
      (dolist (parameter '(popup no-other-window dwindle-ignore no-delete-other-windows
                           split-window delete-window delete-other-windows))
        (set-window-parameter parent parameter
                              (if (memq parameter '(split-window delete-window delete-other-windows))
                                  callback t))
        (should-not (dwindle--managed-window-p ordinary))
        (should-not (dwindle--managed-window-p other))
        (set-window-parameter parent parameter nil))
      (should (dwindle--managed-window-p ordinary))
      (should (dwindle--managed-window-p other))
      (should (= calls 0))
      (window-make-atom (window-parent other))
      (should-not (dwindle--managed-window-p ordinary))
      (should-not (dwindle--managed-window-p other)))))

(ert-deftest dwindle-mode-preserves-and-restores-the-preferred-splitter ()
  (let ((previous-mode dwindle-mode)
        (split-window-preferred-function #'ignore))
    (unwind-protect
        (progn
          (dwindle-mode -1)
          (setq split-window-preferred-function #'ignore)
          (let ((before (dwindle-test--snapshot)))
            (dwindle-mode 1)
            (should (equal before (dwindle-test--snapshot)))
            (should-not (eq split-window-preferred-function #'ignore))
            ;; Enabling twice must not overwrite the saved original.
            (dwindle-mode 1)
            (dwindle-mode -1)
            (should (eq split-window-preferred-function #'ignore))
            (should (equal before (dwindle-test--snapshot)))))
      (dwindle-mode -1)
      (when previous-mode (dwindle-mode 1)))))

(ert-deftest dwindle-disabling-preserves-a-later-third-party-splitter ()
  (dwindle-test--with-layout
    (setq-default split-window-preferred-function #'ignore)
    (dwindle-mode -1)
    (should (eq (default-value 'split-window-preferred-function) #'ignore))))

(ert-deftest dwindle-super-keybindings-use-hjkl-and-unshifted-rotate ()
  (dwindle-test--with-layout
    (dolist (entry '(("s-h" . windmove-left)
                     ("s-j" . windmove-down)
                     ("s-k" . windmove-up)
                     ("s-l" . windmove-right)
                     ("s-H" . dwindle-expand-left)
                     ("s-J" . dwindle-expand-down)
                     ("s-K" . dwindle-expand-up)
                     ("s-L" . dwindle-expand-right)
                     ("C-s-h" . dwindle-shrink-left)
                     ("C-s-j" . dwindle-shrink-down)
                     ("C-s-k" . dwindle-shrink-up)
                     ("C-s-l" . dwindle-shrink-right)
                     ("s-r" . dwindle-rotate)
                     ("s-E" . dwindle-new-buffer)
                     ("s-<return>" . dwindle-new-terminal)
                     ("s-RET" . dwindle-new-terminal)
                     ("s-S-<return>" . dwindle-new-persistent-terminal)
                     ("s-S-RET" . dwindle-new-persistent-terminal)))
      (should (eq (key-binding (kbd (car entry))) (cdr entry))))
    (should-not (eq (key-binding (kbd "s-R")) #'dwindle-rotate))))

(ert-deftest dwindle-new-buffer-creates-a-fresh-empty-buffer-on-each-call ()
  (dwindle-test--with-layout
    (let ((source (selected-window))
          created)
      (unwind-protect
          (let* ((first (dwindle-new-buffer))
                 (first-buffer (window-buffer first)))
            (push first-buffer created)
            (should (eq (selected-window) first))
            (should-not (eq first-buffer (window-buffer source)))
            (with-current-buffer first-buffer
              (should (= (buffer-size) 0))
              (should-not buffer-file-name)
              (insert "Keep the first scratch buffer.\n"))
            (select-window source)
            (let* ((second (dwindle-new-buffer))
                   (second-buffer (window-buffer second)))
              (push second-buffer created)
              (should (eq (selected-window) second))
              (should-not (eq first-buffer second-buffer))
              (with-current-buffer second-buffer
                (should (= (buffer-size) 0))
                (should-not buffer-file-name))
              (with-current-buffer first-buffer
                (should (equal (buffer-string) "Keep the first scratch buffer.\n")))
              (should (window-live-p source))
              (should (window-live-p first))
              (should (= (length (window-list nil 'nomini)) 3))))
        (dolist (buffer created)
          (when (buffer-live-p buffer)
            (with-current-buffer buffer (set-buffer-modified-p nil))
            (kill-buffer buffer)))))))

(ert-deftest dwindle-new-window-commands-inherit-the-focused-buffers-directory ()
  (dolist (command '(dwindle-new-buffer dwindle-new-terminal))
    (dwindle-test--with-layout
      (let* ((directory (file-name-as-directory (make-temp-file "dwindle-focused-dir-" t)))
             (source (generate-new-buffer " *dwindle-directory-source*"))
             (decoy (generate-new-buffer " *dwindle-directory-decoy*"))
             (native-require (symbol-function 'require))
             new-buffer factory-directory)
        (unwind-protect
            (progn
              (set-window-buffer (selected-window) source)
              (with-current-buffer source (setq default-directory directory))
              (with-current-buffer decoy (setq default-directory "/"))
              (cl-letf (((symbol-function 'require)
                         (lambda (feature &rest args)
                           (if (eq feature 'ghostel) 'ghostel
                             (apply native-require feature args))))
                        ((symbol-function 'ghostel-create)
                         (lambda (argument display &optional identity)
                           (should-not argument)
                           (should-not identity)
                           (setq factory-directory default-directory
                                 new-buffer (generate-new-buffer " *dwindle-directory-terminal*"))
                           (with-current-buffer new-buffer
                             (setq default-directory factory-directory))
                           (funcall (car display) new-buffer nil)
                           new-buffer)))
                (let ((new (with-current-buffer decoy (funcall command))))
                  (setq new-buffer (window-buffer new))
                  (should (eq (selected-window) new))
                  (should (equal (buffer-local-value 'default-directory new-buffer) directory))
                  (when (eq command 'dwindle-new-terminal)
                    (should (equal factory-directory directory))))))
          (dolist (buffer (list new-buffer source decoy))
            (when (buffer-live-p buffer) (kill-buffer buffer)))
          (delete-directory directory))))))

(ert-deftest dwindle-new-terminal-is-fresh-and-uses-only-its-dwindle-display-action ()
  (dwindle-test--with-layout
    (let* ((native-require (symbol-function 'require))
           (source (selected-window))
           (existing (generate-new-buffer " *dwindle-existing-terminal*"))
           (popup-action (list #'display-buffer-in-side-window '(side . bottom)))
           (display-buffer-alist (list (cons ".*" popup-action)))
           (display-buffer-overriding-action popup-action)
           created windows)
      (unwind-protect
          (cl-letf (((symbol-function 'require)
                     (lambda (feature &rest args)
                       (if (eq feature 'ghostel) 'ghostel
                         (apply native-require feature args))))
                    ((symbol-function 'ghostel-create)
                     (lambda (argument display &optional identity)
                       ;; The public nil argument means create a new terminal.
                       (should-not argument)
                       (should-not identity)
                       (should-not display-buffer-alist)
                       (should-not display-buffer-overriding-action)
                       (let ((buffer (generate-new-buffer " *dwindle-fresh-terminal*")))
                         (push buffer created)
                         (should (listp display))
                         (let ((new (funcall (car display) buffer nil)))
                           (should (window-live-p new))
                           (should (eq (window-buffer new) buffer))
                           (should (eq (selected-window) new)))
                         buffer))))
            (dotimes (_ 2)
              (select-window source)
              (push (dwindle-new-terminal) windows))
            (should (= (length created) 2))
            (should-not (eq (car created) (cadr created)))
            (should-not (memq existing created))
            (should (window-live-p source))
            (should (cl-every #'window-live-p windows))
            (should (= (length (window-list nil 'nomini)) 3))
            (should (cl-every (lambda (window) (not (window-parameter window 'window-side)))
                              windows))
            (should (eq display-buffer-overriding-action popup-action))
            (should (equal display-buffer-alist (list (cons ".*" popup-action)))))
        (dolist (buffer (cons existing created))
          (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(ert-deftest dwindle-new-window-commands-clean-up-after-native-split-refusal ()
  (dolist (command '(dwindle-new-buffer dwindle-new-terminal))
    (dwindle-test--with-layout
      (let ((native-require (symbol-function 'require))
            (window-min-width 300)
            (window-min-height 150)
            (source (selected-window))
            (before (dwindle-test--snapshot))
            (buffers-before (buffer-list))
            terminal-buffer)
        (cl-letf (((symbol-function 'require)
                   (lambda (feature &rest args)
                     (if (eq feature 'ghostel) 'ghostel
                       (apply native-require feature args))))
                  ((symbol-function 'ghostel-create)
                   (lambda (_argument display &optional _identity)
                     (setq terminal-buffer (generate-new-buffer " *dwindle-refused-terminal*"))
                     (funcall (car display) terminal-buffer nil)
                     terminal-buffer)))
          (should-error (funcall command)))
        (should (eq (selected-window) source))
        (should (equal (dwindle-test--snapshot) before))
        (should-not (cl-set-difference (buffer-list) buffers-before))
        (when terminal-buffer (should-not (buffer-live-p terminal-buffer)))))))

(ert-deftest dwindle-new-terminal-launch-failure-cleans-up-without-prompting ()
  (dwindle-test--with-layout
    (let* ((native-require (symbol-function 'require))
           (previous (generate-new-buffer " *dwindle-previous-terminal*"))
           (previous-process (make-pipe-process :name "dwindle-previous-terminal"
                                               :buffer previous :noquery t))
           (source (selected-window))
           (before (dwindle-test--snapshot))
           failed-buffer failed-process cleanup-hook-ran)
      (unwind-protect
          (cl-letf (((symbol-function 'require)
                     (lambda (feature &rest args)
                       (if (eq feature 'ghostel) 'ghostel
                         (apply native-require feature args))))
                    ((symbol-function 'ghostel-create)
                     (lambda (_argument display &optional _identity)
                       (setq failed-buffer (generate-new-buffer " *dwindle-failed-terminal*"))
                       (funcall (car display) failed-buffer nil)
                       (setq failed-process
                             (make-pipe-process :name "dwindle-failed-terminal"
                                                :buffer failed-buffer :noquery nil))
                       (with-current-buffer failed-buffer
                         (add-hook 'kill-buffer-hook (lambda () (setq cleanup-hook-ran t)) nil t))
                       (error "Injected Ghostel launch failure")))
                    ((symbol-function 'yes-or-no-p)
                     (lambda (&rest _) (ert-fail "Terminal cleanup must not prompt")))
                    ((symbol-function 'y-or-n-p)
                     (lambda (&rest _) (ert-fail "Terminal cleanup must not prompt"))))
            (should (equal (should-error (dwindle-new-terminal))
                           '(error "Injected Ghostel launch failure")))
            (should (eq (selected-window) source))
            (should (equal (dwindle-test--snapshot) before))
            (should cleanup-hook-ran)
            (should-not (buffer-live-p failed-buffer))
            (should-not (process-live-p failed-process))
            (should (buffer-live-p previous))
            (should (process-live-p previous-process)))
        (dolist (buffer (list failed-buffer previous))
          (when (buffer-live-p buffer)
            (let ((kill-buffer-query-functions nil))
              (kill-buffer buffer))))))))

(ert-deftest dwindle-final-selection-hooks-cannot-reenter-window-creation ()
  (dolist (command '(dwindle-new-buffer dwindle-new-terminal dwindle-split))
    (dolist (focus '(leaf internal))
      (dwindle-test--with-layout
        (when (eq focus 'internal)
          (dwindle-test--create 3)
          (should-not (window-live-p (dwindle-focus-parent))))
        (let* ((native-require (symbol-function 'require))
               (original-windows (window-list nil 'nomini))
               (original-buffers (buffer-list))
               (target (when (eq command 'dwindle-split)
                         (generate-new-buffer " *dwindle-selection-target*")))
               (callbacks 0)
               guarded errors attempting)
          (unwind-protect
              (cl-letf (((symbol-function 'require)
                         (lambda (feature &rest args)
                           (if (eq feature 'ghostel) 'ghostel
                             (apply native-require feature args))))
                        ((symbol-function 'ghostel-create)
                         (lambda (_argument display &optional _identity)
                           (let ((buffer (generate-new-buffer " *dwindle-selection-terminal*")))
                             (funcall (car display) buffer nil)
                             buffer))))
                (let ((buffer-list-update-hook
                       (list
                        (lambda ()
                          (unless (memq (selected-window) original-windows)
                            (cl-incf callbacks)
                            (push dwindle--inhibit guarded)
                            ;; Cap recursion even when testing a broken guard,
                            ;; so this regression itself cannot loop forever.
                            (unless attempting
                              (setq attempting t)
                              (unwind-protect
                                  (condition-case error
                                      (dwindle-new-buffer)
                                    (user-error (push error errors)))
                                (setq attempting nil))))))))
                  (let ((new (if target (dwindle-split target) (funcall command))))
                    (should (window-live-p new))
                    (should (eq (selected-window) new))))
                (should (> callbacks 0))
                (should (cl-every #'identity guarded))
                (should (= callbacks (length errors)))
                (should (cl-every (lambda (error)
                                   (string-match-p "already in progress" (error-message-string error)))
                                 errors))
                (should (= (length (window-list nil 'nomini)) (1+ (length original-windows))))
                (should (= (length (cl-set-difference (buffer-list) original-buffers)) 1)))
            (dolist (buffer (cl-set-difference (buffer-list) original-buffers))
              (when (buffer-live-p buffer)
                (with-current-buffer buffer (set-buffer-modified-p nil))
                (kill-buffer buffer)))))))))

(ert-deftest dwindle-failed-terminal-cleanup-continues-after-a-throwing-kill-hook ()
  (dwindle-test--with-layout
    (let* ((native-require (symbol-function 'require))
           (source (selected-window))
           (source-buffer (generate-new-buffer " *dwindle-cleanup-editor*"))
           (source-kill-hook-ran nil)
           (source-kill-hook (list (lambda ()
                                     (setq source-kill-hook-ran t)
                                     (error "Editor cleanup hook must not run"))))
           before failed-buffer failed-process later-hook-ran)
      (unwind-protect
          (progn
            (set-window-buffer source source-buffer)
            (with-current-buffer source-buffer
              (insert "Keep the editor buffer intact.\n")
              (set-buffer-modified-p nil)
              (setq-local kill-buffer-hook source-kill-hook))
            (setq before (dwindle-test--snapshot))
            (cl-letf (((symbol-function 'require)
                     (lambda (feature &rest args)
                       (if (eq feature 'ghostel) 'ghostel
                         (apply native-require feature args))))
                    ((symbol-function 'ghostel-create)
                     (lambda (_argument display &optional _identity)
                       (setq failed-buffer (generate-new-buffer " *dwindle-throwing-cleanup*"))
                       (funcall (car display) failed-buffer nil)
                       (setq failed-process
                             (make-pipe-process :name "dwindle-throwing-cleanup"
                                                :buffer failed-buffer :noquery nil))
                       (with-current-buffer failed-buffer
                         (setq-local kill-buffer-hook
                                     (list (lambda () (error "Injected cleanup hook failure"))
                                           (lambda () (set-buffer source-buffer))
                                           (lambda ()
                                             ;; Cleanup code must see its own
                                             ;; buffer and locals even if an
                                             ;; earlier hook switched buffers.
                                             (should (eq (current-buffer) failed-buffer))
                                             (should (eq (get-buffer-process (current-buffer)) failed-process))
                                             (setq later-hook-ran t)
                                             (delete-process failed-process)))))
                       (error "Original terminal initialization failure"))))
            (should (equal (should-error (dwindle-new-terminal))
                           '(error "Original terminal initialization failure")))
            (should later-hook-ran)
            (should-not (buffer-live-p failed-buffer))
            (should-not (process-live-p failed-process))
            (should (eq (selected-window) source))
            (should (equal (dwindle-test--snapshot) before))
            (should-not source-kill-hook-ran)
            (should (buffer-live-p source-buffer))
            (should (eq (buffer-local-value 'kill-buffer-hook source-buffer) source-kill-hook))
            (with-current-buffer source-buffer
              (should (equal (buffer-string) "Keep the editor buffer intact.\n")))))
        (dolist (buffer (list failed-buffer source-buffer))
          (when (buffer-live-p buffer)
            (with-current-buffer buffer
              (let ((kill-buffer-hook nil)
                    (kill-buffer-query-functions nil))
                (kill-buffer buffer)))))))))

(ert-deftest dwindle-directional-resize-moves-the-requested-edge ()
  (dolist (direction '(left right up down))
    (dolist (operation '(expand shrink))
      (dwindle-test--with-layout
        (let* ((horizontal (memq direction '(left right)))
               (first (selected-window))
               (second (split-window first nil (if horizontal 'right 'below)))
               (selected (if (memq direction '(left up)) second first))
               (measure (if horizontal #'window-total-width #'window-total-height))
               (command (intern (format "dwindle-%s-%s" operation direction))))
          (select-window selected)
          (let ((before (funcall measure selected)))
            (should (numberp (funcall command)))
            (should (funcall (if (eq operation 'expand) #'> #'<)
                             (funcall measure selected) before))
            (should (= (length (dwindle-test--windows)) 2))))))))

(ert-deftest dwindle-expand-at-an-outer-edge-shrinks-from-the-opposite-edge ()
  ;; XMonad BSP deliberately maps an impossible ExpandTowards direction
  ;; to ShrinkFrom in the opposite direction, reducing the focused pane.
  (dolist (direction '(left right up down))
    (dwindle-test--with-layout
      (let* ((horizontal (memq direction '(left right)))
             (first (selected-window))
             (second (split-window first nil (if horizontal 'right 'below)))
             (selected (if (memq direction '(left up)) first second))
             (measure (if horizontal #'window-total-width #'window-total-height))
             (command (intern (format "dwindle-expand-%s" direction))))
        (select-window selected)
        (let ((before (funcall measure selected)))
          (should (numberp (funcall command)))
          (should (< (funcall measure selected) before)))))))

(ert-deftest dwindle-shrink-at-an-outer-edge-does-nothing ()
  (dolist (direction '(left right up down))
    (dwindle-test--with-layout
      (let* ((horizontal (memq direction '(left right)))
             (first (selected-window))
             (second (split-window first nil (if horizontal 'right 'below))))
        (select-window (if (memq direction '(left up)) first second))
        (let ((before (dwindle-test--snapshot)))
          (should-not (funcall (intern (format "dwindle-shrink-%s" direction))))
          (should (equal before (dwindle-test--snapshot))))))))

(ert-deftest dwindle-nested-resize-finds-the-ancestor-sharing-the-edge ()
  (dwindle-test--with-layout
    (let* ((left (selected-window))
           (top-right (split-window left nil 'right))
           (bottom-right (split-window top-right nil 'below))
           (left-width (window-total-width left))
           (right-width (window-total-width top-right))
           (top-height (window-total-height top-right))
           (bottom-height (window-total-height bottom-right)))
      (select-window bottom-right)
      (dwindle-expand-left)
      (should (< (window-total-width left) left-width))
      (should (> (window-total-width top-right) right-width))
      (should (= (window-total-width top-right) (window-total-width bottom-right)))
      (should (= (window-total-height top-right) top-height))
      (should (= (window-total-height bottom-right) bottom-height))
      (let ((left-edges (window-edges left)))
        (dwindle-expand-up)
        (should (equal (window-edges left) left-edges))
        (should (< (window-total-height top-right) top-height))
        (should (> (window-total-height bottom-right) bottom-height))))))

(ert-deftest dwindle-resize-clamps-large-prefixes-and-respects-minimum-size ()
  (dwindle-test--with-layout
    (let* ((left (selected-window))
           (total (window-total-width left))
           (right (split-window left nil 'right)))
      (select-window left)
      (dwindle-expand-right 10000)
      (should (<= (window-total-width left) (ceiling (* total 0.9))))
      (should (> (window-total-width left) (* total 0.8)))
      (dwindle-shrink-right 10000)
      (should (>= (window-total-width left) (floor (* total 0.1))))
      (should (< (window-total-width left) (* total 0.2)))
      (let ((window-min-width 30))
        (dwindle-expand-right 10000)
        (should (>= (window-total-width right) window-min-width))))))

(ert-deftest dwindle-resize-does-not-cross-an-unmanaged-sibling ()
  (dwindle-test--with-layout
    (let* ((left (selected-window))
           (right (split-window left nil 'right)))
      (set-window-dedicated-p right t)
      (select-window left)
      (let ((before (dwindle-test--snapshot)))
        (should-not (dwindle-expand-right))
        (should-not (dwindle-shrink-right))
        (should (equal before (dwindle-test--snapshot)))))))

(ert-deftest dwindle-resize-honors-a-siblings-fixed-width ()
  (dwindle-test--with-layout
    (let* ((left (selected-window))
           (right (split-window left nil 'right))
           (buffer (generate-new-buffer " *dwindle-fixed*")))
      (unwind-protect
          (progn
            (set-window-buffer right buffer)
            (with-current-buffer buffer
              (setq-local window-size-fixed 'width))
            (select-window left)
            (let ((before (dwindle-test--snapshot)))
              (should-not (dwindle-expand-right))
              (should-not (dwindle-shrink-right))
              (should (equal before (dwindle-test--snapshot)))))
        (kill-buffer buffer)))))

(ert-deftest dwindle-resize-single-window-and-invalid-counts-are-safe ()
  (dwindle-test--with-layout
    (let ((before (dwindle-test--snapshot)))
      (dolist (direction '(left right up down))
        (should-not (funcall (intern (format "dwindle-expand-%s" direction))))
        (should-not (funcall (intern (format "dwindle-shrink-%s" direction)))))
      (should (equal before (dwindle-test--snapshot)))
      (dolist (count '(0 -1 "bad"))
        (should-error (dwindle-expand-right count) :type 'user-error)))))

(ert-deftest dwindle-failed-buffer-initialization-rolls-back-only-the-new-window ()
  (dwindle-test--with-layout
    (let* ((windows (dwindle-test--create 3))
           (before (dwindle-test--snapshot))
           (selected (selected-window))
           (original (symbol-function 'set-window-buffer)))
      (cl-letf (((symbol-function 'set-window-buffer)
                 (lambda (window &rest args)
                   (if (memq window windows)
                       (apply original window args)
                     (error "Injected buffer initialization failure")))))
        (should-error (dwindle-split)))
      (should (equal before (dwindle-test--snapshot)))
      (should (eq selected (selected-window)))
      (should (cl-every #'window-live-p windows))
      (dwindle-test--assert-native-root)
      (should (window-live-p (dwindle-split))))))

(ert-deftest dwindle-synchronous-native-split-hook-failure-leaves-no-orphan ()
  (dwindle-test--with-layout
    (let ((source (selected-window))
          (before (dwindle-test--snapshot))
          (buffer (generate-new-buffer " *dwindle-scroll-failure*"))
          (window-scroll-functions
           (list (lambda (&rest _) (error "Injected native scroll hook failure")))))
      (unwind-protect
          (progn
            ;; Native split-window can create its child, invoke this hook,
            ;; and signal before returning that child's identity to Lisp.
            (should-error (dwindle-split))
            (should (eq (selected-window) source))
            (should (equal (dwindle-test--snapshot) before))
            (should-not (funcall split-window-preferred-function source))
            (should (equal (dwindle-test--snapshot) before))
            (should-not (display-buffer-pop-up-window buffer nil))
            (should (equal (dwindle-test--snapshot) before))
            (should (eq (selected-window) source)))
        (kill-buffer buffer)))))

(ert-deftest dwindle-buffer-callback-cannot-silently-insert-an-extra-pane ()
  (dwindle-test--with-layout
    (let* ((windows (dwindle-test--create 2))
           (source (selected-window))
           (root (dwindle-root-window))
           (before (dwindle-test--snapshot))
           (buffer (generate-new-buffer " *dwindle-extra-pane*"))
           extra fired)
      (unwind-protect
          (progn
            (with-current-buffer buffer
              (setq-local
               window-scroll-functions
               (list (lambda (window _start)
                       (unless fired
                         (setq fired t)
                         ;; This is native application behavior, not a
                         ;; reentrant dwindle command, and returns normally.
                         (setq extra (split-window window nil 'right)))))))
            (should-error (dwindle-split buffer))
            (should fired)
            (should (windowp extra))
            (should-not (window-live-p extra))
            (should (cl-every #'window-live-p windows))
            (should (eq (selected-window) source))
            (should (eq (dwindle-root-window) root))
            (should (equal (dwindle-test--snapshot) before)))
        (kill-buffer buffer)))))

(ert-deftest dwindle-buffer-local-hook-cannot-poison-rollback-or-delete-old-windows ()
  (dolist (poison '(atomic delete-override))
    (dwindle-test--with-layout
      (let* ((windows (dwindle-test--create 2))
             (source (selected-window))
             (root (dwindle-root-window))
             (root-parameters (copy-tree (cl-remove-if-not #'cdr (window-parameters root))))
             (before (dwindle-test--snapshot))
             (buffer (generate-new-buffer " *dwindle-poisoned-scroll*")))
        (unwind-protect
            (progn
              (set-window-parameter source 'dwindle-test-marker 'keep)
              (with-current-buffer buffer
                (setq-local
                 window-scroll-functions
                 (list (lambda (window _start)
                         (pcase poison
                           ('atomic (window-make-atom (window-parent window)))
                           ('delete-override
                            (set-window-parameter window 'delete-window #'ignore)))
                         (error "Injected buffer-local rollback poison")))))
              (should-error (dwindle-split buffer))
              (should (cl-every #'window-live-p windows))
              (should (eq (selected-window) source))
              (should (equal (dwindle-test--snapshot) before))
              (should (eq (dwindle-root-window) root))
              (should (equal (cl-remove-if-not #'cdr (window-parameters root))
                             root-parameters))
              (should (eq (window-parameter source 'dwindle-test-marker) 'keep))
              (dolist (window windows)
                (should-not (window-atom-root window))
                (should (dwindle--managed-window-p window)))
              ;; Failed hooks must not leave a guard or native tree poisoned.
              (should (window-live-p (dwindle-split))))
          (kill-buffer buffer))))))

(ert-deftest dwindle-reentrant-display-during-a-split-is-bounded ()
  (dwindle-test--with-layout
    (let ((original (symbol-function 'set-window-buffer))
          (calls 0))
      (cl-letf (((symbol-function 'set-window-buffer)
                 (lambda (&rest args)
                   (cl-incf calls)
                   ;; Simulate a display callback reentering both entry points.
                   (should-not (funcall split-window-preferred-function
                                        (selected-window)))
                   (should-error (dwindle-split) :type 'user-error)
                   (should-error (dwindle-delete-window) :type 'user-error)
                   (apply original args))))
        (should (window-live-p (dwindle-split))))
      (should (= calls 1))
      (should (= (length (dwindle-test--windows)) 2))
      ;; The reentrancy guard must unwind after both success and errors.
      (should (window-live-p (dwindle-split)))
      (should (= (length (dwindle-test--windows)) 3)))))

(ert-deftest dwindle-split-preserves-cyclic-application-parameters ()
  (dwindle-test--with-layout
    (let ((source (selected-window))
          (cycle (list 'application-owned)))
      (setcdr cycle cycle)
      (set-window-parameter source 'dwindle-test-cycle cycle)
      (should (window-live-p (dwindle-split)))
      (should (eq (window-parameter source 'dwindle-test-cycle) cycle))
      (let ((before (dwindle-test--snapshot))
            (window-scroll-functions
             (list (lambda (&rest _) (error "Injected cyclic-parameter rollback failure")))))
        (should-error (dwindle-split))
        (should (equal (dwindle-test--snapshot) before))
        (should (eq (window-parameter source 'dwindle-test-cycle) cycle))))))

(ert-deftest dwindle-rollback-suppresses-and-restores-buffer-local-and-global-hooks ()
  (dwindle-test--with-layout
    (let* ((a (generate-new-buffer " *dwindle-rollback-a*"))
           (b (generate-new-buffer " *dwindle-rollback-b*"))
           (source (selected-window))
           (root (dwindle-root-window))
           (calls 0)
           (global-hook (list (lambda () (cl-incf calls) (error "Hostile global hook"))))
           (local-hook (list (lambda () (cl-incf calls) (error "Hostile local hook"))))
           (previous-default (default-value 'buffer-list-update-hook))
           before view caught)
      (unwind-protect
          (progn
            (with-current-buffer a
              (dotimes (_ 30) (insert "A line long enough to scroll horizontally.\n")))
            (set-window-buffer source a)
            (set-window-point source 120)
            (set-window-start source 43 t)
            (set-window-hscroll source 3)
            (set-window-parameter source 'dwindle-test-marker 'keep)
            (setq before (dwindle-test--snapshot)
                  view (list (window-point source) (window-start source)
                             (window-hscroll source) (window-vscroll source)))
            (condition-case err
                (dwindle--call-with-window-transaction
                 (lambda ()
                   (set-window-buffer source b)
                   (split-window source nil 'right)
                   (set-window-parameter source 'popup 'poison)
                   (set-window-parameter source 'dwindle-test-marker 'damaged)
                   ;; Installing these after the mutation isolates rollback:
                   ;; restoring A runs its local hook in native Emacs.
                   (setq-default buffer-list-update-hook global-hook)
                   (with-current-buffer a
                     (setq-local buffer-list-update-hook local-hook))
                   (error "Original operation failure")))
              (error (setq caught err)))
            (should (equal caught '(error "Original operation failure")))
            (should (equal before (dwindle-test--snapshot)))
            (should (equal view (list (window-point source) (window-start source)
                                      (window-hscroll source) (window-vscroll source))))
            (should (eq source (selected-window)))
            (should (eq root (dwindle-root-window)))
            (should (eq (window-parameter source 'dwindle-test-marker) 'keep))
            (should-not (window-parameter source 'popup))
            (should (= calls 0))
            (should (eq (default-value 'buffer-list-update-hook) global-hook))
            (should (eq (buffer-local-value 'buffer-list-update-hook a) local-hook)))
        (setq-default buffer-list-update-hook previous-default)
        (with-current-buffer a (setq-local buffer-list-update-hook nil))
        (kill-buffer a)
        (kill-buffer b)))))

(ert-deftest dwindle-configuration-hook-only-observes-the-live-tree ()
  (dwindle-test--with-layout
    (dwindle-test--create 5)
    (let ((before (dwindle-test--snapshot))
          (selected (selected-window)))
      (dotimes (_ 20)
        (run-hooks 'window-configuration-change-hook))
      (should (equal before (dwindle-test--snapshot)))
      (should (eq selected (selected-window))))))

(ert-deftest dwindle-preferred-split-preserves-selection-and-refuses-full-windows ()
  (dwindle-test--with-layout
    (let ((source (selected-window)))
      (let ((new (funcall split-window-preferred-function source)))
        (should (window-live-p new))
        (should-not (dwindle--owned-window-p new)))
      (should (eq source (selected-window)))
      (let ((window-min-width 300)
            (window-min-height 150)
            (before (dwindle-test--snapshot)))
        (should-not (funcall split-window-preferred-function source))
        (should (equal before (dwindle-test--snapshot)))))))

(ert-deftest dwindle-preferred-split-restores-selection-after-buffer-callbacks ()
  (dwindle-test--with-layout
    (let ((source (selected-window))
          (original (symbol-function 'set-window-buffer)))
      (cl-letf (((symbol-function 'set-window-buffer)
                 (lambda (window &rest args)
                   (apply original window args)
                   ;; Buffer setup can invoke third-party code that selects.
                   (select-window window))))
        (let ((new (funcall split-window-preferred-function source)))
          (should (window-live-p new))
          (should (eq (selected-window) source))
          (let ((explicit-new (dwindle-split)))
            (should (window-live-p explicit-new))
            (should (eq explicit-new (selected-window)))))))))

(ert-deftest dwindle-display-buffer-pop-up-window-splits-focus-without-selecting ()
  (dwindle-test--with-layout
    (let* ((windows (dwindle-test--create 3))
           (master (car windows))
           (others (mapcar (lambda (window) (list window (window-edges window)))
                           (cdr windows)))
           (buffer (generate-new-buffer " *dwindle-display*")))
      (unwind-protect
          (progn
            (select-window master)
            (let ((new (display-buffer-pop-up-window buffer nil)))
              (should (window-live-p new))
              (should (eq (window-buffer new) buffer))
              (should (eq (selected-window) master))
              (should (dwindle--owned-window-p master))
              (should-not (dwindle--owned-window-p new))
              (should (equal (window-list nil 'nomini (frame-first-window))
                             (append (list master new) (cdr windows))))
              (dolist (other others)
                (should (equal (window-edges (car other)) (cadr other))))))
        (kill-buffer buffer)))))

(ert-deftest dwindle-mode-does-not-adopt-preexisting-ordinary-siblings ()
  (dwindle-test--with-layout
    (dwindle-mode -1)
    (let* ((editor (selected-window))
           (existing (split-window editor nil 'right))
           (before (dwindle-test--snapshot)))
      (select-window editor)
      (dwindle-mode 1)
      (should (dwindle--owned-window-p editor))
      (should (dwindle--managed-window-p existing))
      (should-not (dwindle--owned-window-p existing))
      (should (equal (dwindle-test--snapshot) before))
      (should-not (dwindle-rotate))
      (should (equal (dwindle-test--snapshot) before)))))

(ert-deftest dwindle-unmarked-external-window-is-protected-without-package-cooperation ()
  (dwindle-test--with-layout
    (let* ((editor (selected-window))
           (external (split-window editor nil 'right))
           (buffer (generate-new-buffer " *dwindle-opaque-package-window*")))
      (unwind-protect
          (progn
            ;; A package may retain this exact window object without setting
            ;; popup, dedicated, side-window, or dwindle-specific parameters.
            (set-window-buffer external buffer)
            (should (dwindle--managed-window-p external))
            (should-not (dwindle--owned-window-p external))
            (let ((before (dwindle-test--snapshot)))
              (dolist (focused (list editor external))
                (select-window focused)
                (if (eq focused editor)
                    (should-not (dwindle-rotate))
                  (should-error (dwindle-rotate) :type 'user-error))
                (should (window-live-p external))
                (should (eq (window-buffer external) buffer))
                (should (equal (dwindle-test--snapshot) before))))
            ;; An explicit user split is the point at which this pane is
            ;; deliberately adopted into the user's BSP tree.
            (select-window external)
            (let ((new (dwindle-split)))
              (should (dwindle--owned-window-p external))
              (should (dwindle--owned-window-p new))))
        (kill-buffer buffer)))))

(ert-deftest dwindle-automatic-display-with-internal-focus-keeps-existing-window-objects ()
  (dwindle-test--with-layout
    (let* ((windows (dwindle-test--create 3))
           (master (car windows))
           (focused (caddr windows))
           (focused-edges (window-edges focused nil nil t))
           (outside (mapcar (lambda (window)
                              (list window (window-buffer window)
                                    (window-edges window nil nil t)))
                            (butlast windows)))
           (root (dwindle-root-window)))
      (select-window focused)
      (let ((node (dwindle-focus-parent)))
        (should-not (window-live-p node))
        (let ((new (funcall split-window-preferred-function master)))
          ;; An automatic display action must split just the selected leaf;
          ;; reconstructing the internally focused region would retire old
          ;; window objects that the display action did not ask to replace.
          (should (window-live-p new))
          (should (cl-every #'window-live-p windows))
          (should (cl-every #'dwindle--owned-window-p windows))
          (should-not (dwindle--owned-window-p new))
          (should (eq (selected-window) focused))
          (should (eq (dwindle-root-window) root))
          (should (window-valid-p node))
          (should (equal (window-list nil 'nomini (frame-first-window))
                         (append windows (list new))))
          (should (eq (window-parent new) (window-parent focused)))
          (should (equal (window-edges (window-parent new) nil nil t) focused-edges))
          (dolist (snapshot outside)
            (should (eq (window-buffer (car snapshot)) (nth 1 snapshot)))
            (should (equal (window-edges (car snapshot) nil nil t)
                           (nth 2 snapshot)))))))))

(ert-deftest dwindle-tail-insertion-does-not-claim-an-unmarked-package-target ()
  (dwindle-test--with-layout
    (let* ((dwindle-split-policy 'tail)
           (editor (selected-window))
           (package-window (split-window editor nil 'right))
           (buffer (generate-new-buffer " *dwindle-tail-package-window*")))
      (unwind-protect
          (progn
            (set-window-buffer package-window buffer)
            (should (dwindle--owned-window-p editor))
            (should-not (dwindle--owned-window-p package-window))
            (select-window editor)
            (let ((new (dwindle-split)))
              (should (window-live-p editor))
              (should (window-live-p package-window))
              (should (eq (window-buffer package-window) buffer))
              (should (eq (window-parent package-window) (window-parent new)))
              (should (dwindle--owned-window-p editor))
              (should (dwindle--owned-window-p new))
              (should-not (dwindle--owned-window-p package-window))
              (let ((before (dwindle-test--snapshot)))
                (select-window new)
                (should-not (dwindle-rotate))
                (select-window package-window)
                (should-error (dwindle-rotate) :type 'user-error)
                (should (window-live-p package-window))
                (should (eq (window-buffer package-window) buffer))
                (should-not (dwindle--owned-window-p package-window))
                (should (equal (dwindle-test--snapshot) before)))))
        (kill-buffer buffer)))))

(ert-deftest dwindle-find-file-keeps-editor-ownership-and-alternating-splits ()
  (dwindle-test--with-layout
    (let* ((master (selected-window))
           (editor (dwindle-split))
           (master-edges (window-edges master))
           (file (make-temp-file "dwindle-navigation-" nil ".txt"
                                 "Ordinary file navigation stays in this editor pane.\n"))
           buffer)
      (unwind-protect
          (progn
            (find-file file)
            (setq buffer (find-buffer-visiting file))
            (should (eq (selected-window) editor))
            (should (eq (window-buffer editor) buffer))
            ;; Real find-file installs a native restoration record for this
            ;; existing pane; it must not look like an external popup.
            (should (window-parameter editor 'quit-restore))
            (dwindle--refresh)
            (should (dwindle--managed-window-p editor))
            (should (dwindle--owned-window-p editor))
            (let ((new (dwindle-split)))
              (should (dwindle--owned-window-p new))
              (should (eq (window-buffer new) buffer))
              (should (equal (window-edges master) master-edges))
              (should (= (nth 0 (window-edges editor)) (nth 0 (window-edges new))))
              (should (= (nth 2 (window-edges editor)) (nth 2 (window-edges new))))
              (should (= (nth 3 (window-edges editor)) (nth 1 (window-edges new))))))
        (when (buffer-live-p buffer) (kill-buffer buffer))
        (delete-file file)))))

(ert-deftest dwindle-background-display-reuse-revokes-editor-ownership ()
  (dwindle-test--with-layout
    (let* ((source (selected-window))
           (target (dwindle-split))
           (buffer (generate-new-buffer " *dwindle-background-reuse*")))
      (unwind-protect
          (progn
            (should (dwindle--owned-window-p target))
            (select-window source)
            ;; This is the native final step of an external display action
            ;; that chose an existing pane while another pane has focus.
            (should (eq (window--display-buffer buffer target 'reuse) target))
            (should (eq (selected-window) source))
            (should (eq (window-buffer target) buffer))
            (should (window-parameter target 'quit-restore))
            (dwindle--refresh)
            (should-not (dwindle--managed-window-p target))
            (should-not (dwindle--owned-window-p target))
            ;; Clearing native lifecycle bookkeeping later cannot silently
            ;; re-enroll a pane which an external display action took over.
            (set-window-parameter target 'quit-restore nil)
            (dwindle--refresh)
            (should (dwindle--managed-window-p target))
            (should-not (dwindle--owned-window-p target))
            (let ((before (dwindle-test--snapshot)))
              (should-not (dwindle-rotate))
              (should (equal (dwindle-test--snapshot) before))
              (should (window-live-p target))
              (should (eq (window-buffer target) buffer))))
        (kill-buffer buffer)))))

(ert-deftest dwindle-preferred-split-favors-focus-over-the-suggested-window ()
  (dwindle-test--with-layout
    (let* ((windows (dwindle-test--create 3))
           (master (car windows))
           (focused (cadr windows))
           (tail (caddr windows))
           (master-before (window-edges master))
           (tail-before (window-edges tail)))
      (select-window focused)
      (let ((new (funcall split-window-preferred-function master)))
        (should (window-live-p new))
        (should (eq focused (selected-window)))
        (should (eq (window-parent new) (window-parent focused)))
        (should (equal (window-edges master) master-before))
        (should (equal (window-edges tail) tail-before))))))

(ert-deftest dwindle-refuses-a-full-focused-pane-instead-of-splitting-elsewhere ()
  (dwindle-test--with-layout
    (let* ((windows (dwindle-test--create 3))
           (master (car windows))
           (focused (caddr windows))
           (window-min-width 50)
           (buffer (generate-new-buffer " *dwindle-full-focus*")))
      (unwind-protect
          (let ((before (dwindle-test--snapshot)))
            (select-window focused)
            (should-error (dwindle-split))
            (should-not (funcall split-window-preferred-function master))
            (should-not (display-buffer-pop-up-window buffer nil))
            (should (eq (selected-window) focused))
            (should (equal (dwindle-test--snapshot) before))
            ;; There is room elsewhere; choosing it must be explicit.
            (select-window master)
            (should (window-live-p (dwindle-split))))
        (kill-buffer buffer)))))

(ert-deftest dwindle-foreign-focus-refuses-explicit-and-automatic-insertion ()
  (dolist (kind '(popup no-other-window dedicated custom-split))
    (dwindle-test--with-layout
      (let* ((ordinary (selected-window))
             (foreign (split-window ordinary nil 'right))
             (buffer (generate-new-buffer " *dwindle-foreign-display*")))
        (unwind-protect
            (progn
              (pcase kind
                ('dedicated (set-window-dedicated-p foreign t))
                ('custom-split (set-window-parameter foreign 'split-window #'ignore))
                (_ (set-window-parameter foreign kind t)))
              (select-window foreign)
              (let ((before (dwindle-test--snapshot)))
                (should-error (dwindle-split) :type 'user-error)
                (should-not (funcall split-window-preferred-function ordinary))
                (should-not (display-buffer-pop-up-window buffer nil))
                (should (eq (selected-window) foreign))
                (should (equal (dwindle-test--snapshot) before))
                (select-window ordinary)
                (should-not (funcall split-window-preferred-function foreign))
                (should (equal (dwindle-test--snapshot) before))))
          (kill-buffer buffer))))))

(ert-deftest dwindle-nary-resize-changes-only-the-adjacent-pair ()
  (dolist (direction '(left right up down))
    (dolist (operation '(expand shrink))
      (dwindle-test--with-layout
        (let* ((window-combination-limit nil)
               (horizontal (memq direction '(left right)))
               (side (if horizontal 'right 'below))
               (size (if horizontal 40 20))
               (a (selected-window))
               (b (split-window a size side))
               (c (split-window b size side))
               (d (split-window c size side))
               (focused (if (memq direction '(left up)) c b))
               (measure (if horizontal #'window-total-width #'window-total-height))
               (a-before (window-edges a))
               (d-before (window-edges d))
               (before (funcall measure focused))
               (pair-size (+ (funcall measure b) (funcall measure c))))
          (should (eq (window-parent a) (window-parent d)))
          (select-window focused)
          (should (numberp (funcall (intern (format "dwindle-%s-%s" operation direction)))))
          (should (funcall (if (eq operation 'expand) #'> #'<)
                           (funcall measure focused) before))
          (should (= (+ (funcall measure b) (funcall measure c)) pair-size))
          (should (equal (window-edges a) a-before))
          (should (equal (window-edges d) d-before)))))))

(ert-deftest dwindle-nary-resize-preserves-unrelated-foreign-siblings ()
  (dwindle-test--with-layout
    (let* ((window-combination-limit nil)
           (a (selected-window))
           (b (split-window a 40 'right))
           (c (split-window b 40 'right))
           (d (split-window c 40 'right))
           (a-before (window-edges a))
           (d-before (window-edges d)))
      (set-window-dedicated-p a t)
      (set-window-parameter d 'popup t)
      (select-window b)
      (should (numberp (dwindle-expand-right)))
      (should (equal (window-edges a) a-before))
      (should (equal (window-edges d) d-before))
      (should (> (window-total-width b) 40))
      (should (< (window-total-width c) 40))
      (let ((before (dwindle-test--snapshot)))
        (should-not (dwindle-expand-left))
        (should-not (dwindle-shrink-left))
        (should (equal (dwindle-test--snapshot) before))))))

(ert-deftest dwindle-move-split-moves-the-divider-in-the-requested-direction ()
  (dolist (direction '(left right up down))
    (dolist (focus '(first second))
      (dwindle-test--with-layout
        (let* ((horizontal (memq direction '(left right)))
               (first (selected-window))
               (second (split-window first nil (if horizontal 'right 'below)))
               (edge (if horizontal 2 3))
               (before (nth edge (window-edges first)))
               (focused (if (eq focus 'first) first second)))
          (select-window focused)
          (should (numberp (funcall (intern (format "dwindle-move-split-%s" direction)))))
          (should (funcall (if (memq direction '(left up)) #'< #'>)
                           (nth edge (window-edges first)) before))
          (should (eq (selected-window) focused)))))))

(ert-deftest dwindle-move-split-prefers-a-farther-after-boundary-to-a-nearer-before-one ()
  (dwindle-test--with-layout
    (let* ((window-combination-limit t)
           (left (selected-window))
           (right (split-window left 80 'right))
           (focused (split-window left 40 'right))
           (right-before (window-edges right)))
      ;; The focused pane has a direct left sibling, but its right edge is
      ;; shared by the enclosing left subtree and the far-right pane.
      (should-not (eq (window-parent focused) (window-parent right)))
      (select-window focused)
      (should (numberp (dwindle-move-split-left)))
      (should (< (nth 0 (window-edges right)) (nth 0 right-before)))
      (should (= (nth 2 (window-edges right)) (nth 2 right-before)))
      (should (= (nth 2 (window-edges focused)) (nth 0 (window-edges right)))))))

(ert-deftest dwindle-resize-honors-the-focused-internal-node ()
  (dwindle-test--with-layout
    (let* ((left (selected-window))
           (top-right (dwindle-split))
           (bottom-right (dwindle-split))
           (left-width (window-total-width left))
           (right-width (window-total-width top-right)))
      (select-window bottom-right)
      (let ((node (dwindle-focus-parent))
            (before (dwindle-test--snapshot)))
        (should (eq node (window-parent bottom-right)))
        (should-not (window-live-p node))
        ;; Resizing the lower leaf alone could move the horizontal divider.
        ;; The focused whole right subtree has no movable vertical boundary.
        (should-not (dwindle-expand-up))
        (should-not (dwindle-shrink-down))
        (should (equal (dwindle-test--snapshot) before))
        (should (numberp (dwindle-expand-left)))
        (should (< (window-total-width left) left-width))
        (should (> (window-total-width top-right) right-width))
        (should (= (window-total-width top-right) (window-total-width bottom-right)))
        (should (eq (selected-window) bottom-right))
        (should (eq (dwindle--focused-node) node))))))

(ert-deftest dwindle-doom-wrapper-preserves-file-and-read-only-arguments ()
  (dwindle-test--with-layout
    (let (opened native-args)
      (cl-letf (((symbol-function 'evil-edit)
                 (lambda (file &optional _bang) (setq opened (list 'edit file))))
                ((symbol-function 'evil-view)
                 (lambda (file &optional _bang) (setq opened (list 'view file)))))
        (let* ((original (lambda (&rest args) (setq native-args args) 'native))
               (new (dwindle-doom--evil-split original nil "notes.org" nil)))
          (should (window-live-p new))
          (should (eq new (selected-window)))
          (should (equal opened '(edit "notes.org")))
          (should-not native-args)
          (dwindle-doom--evil-split original nil "read-only.org" t)
          (should (equal opened '(view "read-only.org")))
          (should (= (length (dwindle-test--windows)) 3))
          (should (eq (dwindle-doom--evil-split original 12 "sized.org" t)
                      'native))
          (should (equal native-args '(12 "sized.org" t)))
          (should (= (length (dwindle-test--windows)) 3))
          (set-window-parameter (selected-window) 'popup t)
          (should (eq (dwindle-doom--evil-split original nil "popup.org" nil)
                      'native))
          (should (equal native-args '(nil "popup.org" nil))))))))

(ert-deftest dwindle-doom-advice-wraps-doom-overrides-and-removes-only-itself ()
  (dwindle-test--with-layout
    (dwindle-mode -1)
    (cl-letf (((symbol-function 'evil-window-split) (lambda (&rest _) 'native))
              ((symbol-function 'evil-window-vsplit) (lambda (&rest _) 'native)))
      (let ((doom-override (lambda (&rest _) 'doom)))
        (unwind-protect
            (progn
              (dolist (command '(evil-window-split evil-window-vsplit))
                (advice-add command :override doom-override))
              (dwindle-mode 1)
              (should (window-live-p (funcall 'evil-window-split nil)))
              (should (window-live-p (funcall 'evil-window-vsplit nil)))
              (should (eq (funcall 'evil-window-split 10) 'doom))
              (should (= (length (dwindle-test--windows)) 3))
              (dwindle-mode -1)
              (dolist (command '(evil-window-split evil-window-vsplit))
                (should (advice-member-p doom-override command))
                (should (eq (funcall command nil) 'doom))))
          (dwindle-mode -1)
          (dolist (command '(evil-window-split evil-window-vsplit))
            (advice-remove command doom-override)))))))

(provide 'dwindle-tests)
;;; dwindle-tests.el ends here
